#!/usr/bin/php

<?php

error_reporting(0);

$message = $argv[1];

if (empty($message)) {
   echo "Usage: push \"message\"

"; 
   die;
}

curl_setopt_array($ch = curl_init(), array(
  CURLOPT_URL => "https://api.pushover.net/1/messages.json",
  CURLOPT_POSTFIELDS => array(
    "token" => "",
    "user"  => "",
    "message" => $message
  ),
  CURLOPT_SAFE_UPLOAD => true,
  CURLOPT_RETURNTRANSFER => true,
));

curl_exec($ch);
curl_close($ch);

?>
